// Gradualblur.jsx
import React, { useEffect, useRef, useState } from 'react';
import * as math from 'mathjs';

// Preset configurations
const PRESETS = {
  hero: { position: 'bottom', strength: 2.5, height: '8rem', divCount: 6, animated: 'fade' },
  navigation: { position: 'top', strength: 1.5, height: '4rem', divCount: 4, tint: 'rgba(255,255,255,0.1)' },
  modal: { position: 'bottom', strength: 3, height: '100vh', width: '100vw', tint: 'rgba(0,0,0,0.2)' },
  card: { position: 'bottom', strength: 1.8, height: '3rem', divCount: 4, curve: 'bezier' }
};

const GradualBlur = ({ 
  // Basic options
  position = 'bottom',
  strength = 2,
  height = '7rem',
  width = '100%',
  divCount = 5,
  exponential = false,
  zIndex = 1000,
  
  // Animation options
  animated = false,
  duration = '0.3s',
  easing = 'ease-out',
  
  // Styling options
  tint,
  opacity = 1,
  curve = 'linear',
  
  // Responsive options
  responsive = false,
  mobileHeight,
  tabletHeight,
  desktopHeight,
  
  // Advanced options
  preset,
  gpuOptimized = false,
  hoverIntensity,
  
  // Event handlers
  onAnimationComplete,
  className = '',
  style = {}
}) => {
  const containerRef = useRef(null);
  const [isVisible, setIsVisible] = useState(!animated || animated !== 'scroll');
  const [isHovered, setIsHovered] = useState(false);
  
  // Apply preset if specified
  const presetConfig = preset && PRESETS[preset] ? PRESETS[preset] : {};
  
  // Use preset values or fallback to props
  const finalConfig = {
    position: presetConfig.position || position,
    strength: presetConfig.strength || strength,
    height: presetConfig.height || height,
    width: presetConfig.width || width,
    divCount: presetConfig.divCount || divCount,
    exponential: presetConfig.exponential !== undefined ? presetConfig.exponential : exponential,
    zIndex: presetConfig.zIndex || zIndex,
    animated: presetConfig.animated || animated,
    duration: presetConfig.duration || duration,
    easing: presetConfig.easing || easing,
    tint: presetConfig.tint || tint,
    opacity: presetConfig.opacity !== undefined ? presetConfig.opacity : opacity,
    curve: presetConfig.curve || curve,
    hoverIntensity: presetConfig.hoverIntensity || hoverIntensity
  };
  
  // Scroll animation effect
  useEffect(() => {
    if (finalConfig.animated === 'scroll' && containerRef.current) {
      const observer = new IntersectionObserver(
        (entries) => {
          entries.forEach((entry) => {
            setIsVisible(entry.isIntersecting);
            if (entry.isIntersecting && onAnimationComplete) {
              setTimeout(() => onAnimationComplete(), parseFloat(finalConfig.duration) * 1000);
            }
          });
        },
        { threshold: 0.1 }
      );
      
      observer.observe(containerRef.current);
      return () => observer.disconnect();
    }
  }, [finalConfig.animated, finalConfig.duration, onAnimationComplete]);
  
  // Blur progression calculation
  const getBlurProgression = (i, divCount, curve, exponential, strength) => {
    let progress = i / divCount;
    
    switch (curve) {
      case 'bezier':
        progress = progress * progress * (3 - 2 * progress);
        break;
      case 'ease-in-out':
        progress = progress < 0.5 ? 2 * progress * progress : 1 - Math.pow(-2 * progress + 2, 2) / 2;
        break;
      default:
        break;
    }
    
    if (exponential) {
      return math.pow(2, progress * 4) * 0.0625 * strength;
    }
    return 0.0625 * (progress * divCount + 1) * strength;
  };
  
  // Generate gradient direction
  const getGradientDirection = (position) => {
    const directions = {
      top: 'to top',
      bottom: 'to bottom',
      left: 'to left',
      right: 'to right'
    };
    return directions[position] || 'to bottom';
  };

  const generateBlurDivs = () => {
    const divs = [];
    const increment = 100 / finalConfig.divCount;
    const currentStrength = isHovered && finalConfig.hoverIntensity ? 
      finalConfig.strength * finalConfig.hoverIntensity : finalConfig.strength;
    
    for (let i = 1; i <= finalConfig.divCount; i++) {
      const c1 = 'transparent';
      const c2 = 'black';
      
      const p1 = math.round((increment * i - increment) * 10) / 10;
      const p2 = math.round((increment * i) * 10) / 10;
      const p3 = math.round((increment * i + increment) * 10) / 10;
      const p4 = math.round((increment * i + increment * 2) * 10) / 10;
      
      let gradient = `${c1} ${p1}%, ${c2} ${p2}%`;
      
      if (p3 <= 100) {
        gradient = `${c1} ${p1}%, ${c2} ${p2}%, ${c2} ${p3}%`;
      }
      
      if (p4 <= 100) {
        gradient = `${c1} ${p1}%, ${c2} ${p2}%, ${c2} ${p3}%, ${c1} ${p4}%`;
      }
      
      const blurValue = getBlurProgression(i, finalConfig.divCount, finalConfig.curve, finalConfig.exponential, currentStrength);
      const direction = getGradientDirection(finalConfig.position);
      
      const divStyle = {
        position: 'absolute',
        inset: '0',
        maskImage: `linear-gradient(${direction}, ${gradient})`,
        WebkitMaskImage: `linear-gradient(${direction}, ${gradient})`,
        backdropFilter: `blur(${blurValue.toFixed(3)}rem)`,
        opacity: finalConfig.opacity,
        transition: finalConfig.animated && finalConfig.animated !== 'scroll' ? 
          `backdrop-filter ${finalConfig.duration} ${finalConfig.easing}` : undefined
      };
      
      divs.push(<div key={i} style={divStyle}></div>);
    }
    
    return divs;
  };
  
  // Responsive height calculation
  const getResponsiveHeight = () => {
    if (!responsive) return finalConfig.height;
    
    const width = window.innerWidth;
    if (width <= 768 && mobileHeight) return mobileHeight;
    if (width <= 1024 && width > 768 && tabletHeight) return tabletHeight;
    if (width > 1024 && desktopHeight) return desktopHeight;
    return finalConfig.height;
  };

  const containerStyle = {
    height: responsive ? getResponsiveHeight() : finalConfig.height,
    width: finalConfig.width,
    position: 'fixed',
    [finalConfig.position]: 0,
    [finalConfig.position === 'left' || finalConfig.position === 'right' ? 'top' : 'left']: 0,
    zIndex: finalConfig.zIndex,
    pointerEvents: finalConfig.hoverIntensity ? 'auto' : 'none',
    opacity: isVisible ? 1 : 0,
    transition: finalConfig.animated ? `opacity ${finalConfig.duration} ${finalConfig.easing}` : undefined,
    background: finalConfig.tint || undefined,
    willChange: gpuOptimized ? 'transform, opacity' : undefined,
    transform: gpuOptimized ? 'translateZ(0)' : undefined,
    ...style
  };
  
  const innerStyle = {
    position: 'relative',
    width: '100%',
    height: '100%'
  };
  
  const handleMouseEnter = () => {
    if (finalConfig.hoverIntensity) {
      setIsHovered(true);
    }
  };
  
  const handleMouseLeave = () => {
    if (finalConfig.hoverIntensity) {
      setIsHovered(false);
    }
  };

  return (
    <div 
      ref={containerRef}
      className={`gradual-blur ${className}`}
      style={containerStyle}
      onMouseEnter={handleMouseEnter}
      onMouseLeave={handleMouseLeave}
    >
      <div className="gradual-blur-inner" style={innerStyle}>
        {generateBlurDivs()}
      </div>
    </div>
  );
};

export default GradualBlur;

// GradualBlur.vue
<template>
  <div 
    ref="containerRef"
    :class="['gradual-blur', className]"
    :style="containerStyle"
    @mouseenter="handleMouseEnter"
    @mouseleave="handleMouseLeave"
  >
    <div class="gradual-blur-inner" :style="innerStyle">
      <div 
        v-for="(layer, index) in blurLayers" 
        :key="index"
        :style="layer.style"
      ></div>
    </div>
  </div>
</template>

<script>
import { ref, computed, onMounted, onUnmounted, watch } from 'vue'

const PRESETS = {
  hero: { position: 'bottom', strength: 2.5, height: '8rem', divCount: 6, animated: 'fade' },
  navigation: { position: 'top', strength: 1.5, height: '4rem', divCount: 4, tint: 'rgba(255,255,255,0.1)' },
  modal: { position: 'bottom', strength: 3, height: '100vh', width: '100vw', tint: 'rgba(0,0,0,0.2)' },
  card: { position: 'bottom', strength: 1.8, height: '3rem', divCount: 4, curve: 'bezier' }
}

export default {
  name: 'GradualBlur',
  props: {
    position: { type: String, default: 'bottom' },
    strength: { type: Number, default: 2 },
    height: { type: String, default: '7rem' },
    width: { type: String, default: '100%' },
    divCount: { type: Number, default: 5 },
    exponential: { type: Boolean, default: false },
    zIndex: { type: Number, default: 1000 },
    animated: { type: [String, Boolean], default: false },
    duration: { type: String, default: '0.3s' },
    easing: { type: String, default: 'ease-out' },
    tint: { type: String, default: null },
    opacity: { type: Number, default: 1 },
    curve: { type: String, default: 'linear' },
    preset: { type: String, default: null },
    gpuOptimized: { type: Boolean, default: false },
    hoverIntensity: { type: Number, default: null },
    className: { type: String, default: '' }
  },
  emits: ['animationComplete'],
  setup(props, { emit }) {
    const containerRef = ref(null)
    const isVisible = ref(!props.animated || props.animated !== 'scroll')
    const isHovered = ref(false)
    let observer = null

    const finalConfig = computed(() => {
      const presetConfig = props.preset && PRESETS[props.preset] ? PRESETS[props.preset] : {}
      return {
        position: presetConfig.position || props.position,
        strength: presetConfig.strength || props.strength,
        height: presetConfig.height || props.height,
        width: presetConfig.width || props.width,
        divCount: presetConfig.divCount || props.divCount,
        exponential: presetConfig.exponential !== undefined ? presetConfig.exponential : props.exponential,
        zIndex: presetConfig.zIndex || props.zIndex,
        animated: presetConfig.animated || props.animated,
        duration: presetConfig.duration || props.duration,
        easing: presetConfig.easing || props.easing,
        tint: presetConfig.tint || props.tint,
        opacity: presetConfig.opacity !== undefined ? presetConfig.opacity : props.opacity,
        curve: presetConfig.curve || props.curve,
        gpuOptimized: presetConfig.gpuOptimized || props.gpuOptimized,
        hoverIntensity: presetConfig.hoverIntensity || props.hoverIntensity
      }
    })

    const getBlurProgression = (i, divCount, curve, exponential, strength) => {
      let progress = i / divCount
      
      switch (curve) {
        case 'bezier':
          progress = progress * progress * (3 - 2 * progress)
          break
        case 'ease-in-out':
          progress = progress < 0.5 ? 2 * progress * progress : 1 - Math.pow(-2 * progress + 2, 2) / 2
          break
      }
      
      if (exponential) {
        return Math.pow(2, progress * 4) * 0.0625 * strength
      }
      return 0.0625 * (progress * divCount + 1) * strength
    }

    const getGradientDirection = (position) => {
      const directions = {
        top: 'to top',
        bottom: 'to bottom',
        left: 'to left',
        right: 'to right'
      }
      return directions[position] || 'to bottom'
    }

    const blurLayers = computed(() => {
      const layers = []
      const increment = 100 / finalConfig.value.divCount
      const currentStrength = isHovered.value && finalConfig.value.hoverIntensity ? 
        finalConfig.value.strength * finalConfig.value.hoverIntensity : finalConfig.value.strength

      for (let i = 1; i <= finalConfig.value.divCount; i++) {
        const c1 = 'transparent'
        const c2 = 'black'
        
        const p1 = Math.round((increment * i - increment) * 10) / 10
        const p2 = Math.round((increment * i) * 10) / 10
        const p3 = Math.round((increment * i + increment) * 10) / 10
        const p4 = Math.round((increment * i + increment * 2) * 10) / 10
        
        let gradient = `${c1} ${p1}%, ${c2} ${p2}%`
        
        if (p3 <= 100) {
          gradient = `${c1} ${p1}%, ${c2} ${p2}%, ${c2} ${p3}%`
        }
        
        if (p4 <= 100) {
          gradient = `${c1} ${p1}%, ${c2} ${p2}%, ${c2} ${p3}%, ${c1} ${p4}%`
        }
        
        const blurValue = getBlurProgression(i, finalConfig.value.divCount, finalConfig.value.curve, finalConfig.value.exponential, currentStrength)
        const direction = getGradientDirection(finalConfig.value.position)
        
        layers.push({
          style: {
            position: 'absolute',
            inset: '0',
            maskImage: `linear-gradient(${direction}, ${gradient})`,
            WebkitMaskImage: `linear-gradient(${direction}, ${gradient})`,
            backdropFilter: `blur(${blurValue.toFixed(3)}rem)`,
            opacity: finalConfig.value.opacity,
            transition: finalConfig.value.animated && finalConfig.value.animated !== 'scroll' ? 
              `backdrop-filter ${finalConfig.value.duration} ${finalConfig.value.easing}` : undefined
          }
        })
      }
      
      return layers
    })

    const containerStyle = computed(() => {
      const style = {
        height: finalConfig.value.height,
        width: finalConfig.value.width,
        position: 'fixed',
        [finalConfig.value.position]: '0',
        [finalConfig.value.position === 'left' || finalConfig.value.position === 'right' ? 'top' : 'left']: '0',
        zIndex: finalConfig.value.zIndex,
        pointerEvents: finalConfig.value.hoverIntensity ? 'auto' : 'none',
        opacity: isVisible.value ? 1 : 0
      }
      
      if (finalConfig.value.animated) {
        style.transition = `opacity ${finalConfig.value.duration} ${finalConfig.value.easing}`
      }
      
      if (finalConfig.value.tint) {
        style.background = finalConfig.value.tint
      }
      
      if (finalConfig.value.gpuOptimized) {
        style.willChange = 'transform, opacity'
        style.transform = 'translateZ(0)'
      }
      
      return style
    })

    const innerStyle = computed(() => ({
      position: 'relative',
      width: '100%',
      height: '100%'
    }))

    const handleMouseEnter = () => {
      if (finalConfig.value.hoverIntensity) {
        isHovered.value = true
      }
    }

    const handleMouseLeave = () => {
      if (finalConfig.value.hoverIntensity) {
        isHovered.value = false
      }
    }

    onMounted(() => {
      if (finalConfig.value.animated === 'scroll' && containerRef.value) {
        observer = new IntersectionObserver(
          (entries) => {
            entries.forEach((entry) => {
              isVisible.value = entry.isIntersecting
              if (entry.isIntersecting) {
                setTimeout(() => emit('animationComplete'), parseFloat(finalConfig.value.duration) * 1000)
              }
            })
          },
          { threshold: 0.1 }
        )
        
        observer.observe(containerRef.value)
      }
    })

    onUnmounted(() => {
      if (observer) {
        observer.disconnect()
      }
    })

    return {
      containerRef,
      blurLayers,
      containerStyle,
      innerStyle,
      handleMouseEnter,
      handleMouseLeave
    }
  }
}
</script>
